site_name: Neurotech Development Kit
site_url: https://agencyenterprise.github.io/neurotechdevkit/
repo_url: https://github.com/agencyenterprise/neurotechdevkit

theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: indigo
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: indigo
      accent: indigo

nav:
  - Home: index.md
  - Installation: installation.md
  - User Interface: user_interface.md
  - Usage:
      - Scenarios: usage/loading_scenarios.md
      - Sources: usage/defining_sources.md
      - Simulation: usage/running_simulation.md
      - Troubleshooting: usage/troubleshooting.md
      - GPU support: usage/gpu.md
  - API:
      - Scenarios: api/scenarios.md
      - Grid: api/grid.md
      - Problem: api/problem.md
      - Materials: api/materials.md
      - Sources: api/sources.md
      - Results: api/results.md
  - Examples: generated/gallery
  - Contributing: contributing.md

extra_css:
- css/mkdocstrings.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.tilde


plugins:
  - gallery:
      examples_dirs: docs/examples # path to your example scripts
      gallery_dirs: docs/generated/gallery # where to save generated gallery

  - search

  - offline-links:
      enabled: !ENV [OFFLINE, false]


  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
