# Tagging a commit with [circle front] will build the front page and perform tests-doc.
# Tagging a commit with [circle full] will build everything.
version: 2.1
parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

jobs:
  build_docs:
    docker:
      - image: cimg/python:3.10.10
    resource_class: xlarge
    steps:
      - checkout

      - run:
          name: Install ffmpeg dependency
          command: |
            sudo apt-get update && sudo apt-get install -y ffmpeg

      - run:
          name: Install the latest version of Poetry
          command: |
            curl -sSL https://install.python-poetry.org | python3 -

      - run:
          name: Install dependencies
          command: |
            poetry install --no-ansi

      - run:
          name: Install stride
          command: |
            poetry run pip install git+https://github.com/trustimaging/stride

      - restore_cache:
          name: Restore docs cache
          keys:
            - docs-{{ epoch }}
            - docs-

      - run:
          name: Build HTML
          command: |
            OFFLINE=true make docs

      - save_cache:
          key: docs-{{ epoch }}
          paths:
            - docs/generated

      - store_artifacts:
          path: site/
          destination: html


  build_docs_no_cache:
    docker:
      - image: cimg/python:3.10.10
    resource_class: xlarge
    steps:
      - checkout

      - run:
          name: Install the latest version of Poetry
          command: |
            curl -sSL https://install.python-poetry.org | python3 -

      - run:
          name: Install dependencies
          command: |
            poetry install --no-ansi

      - run:
          name: Install stride
          command: |
            poetry run pip install git+https://github.com/trustimaging/stride

      - run:
          name: Build HTML
          command: |
            OFFLINE=true make docs

workflows:
  version: 2

  build_triggered_by_github_action:
    when: << pipeline.parameters.GHA_Action >>
    jobs:
      - build_docs_no_cache

  default:
    jobs:
      - build_docs:
          name: build_docs
