version: 2.1

jobs:
  build_docs_cached:
    docker:
      - image: cimg/python:3.10.10
    resource_class: xlarge
    steps:
      - checkout

      - run:
          name: Install ffmpeg dependency
          command: |
            sudo apt-get update && sudo apt-get install -y ffmpeg

      - run:
          name: Install the latest version of Poetry
          command: |
            curl -sSL https://install.python-poetry.org | python3 -

      - run:
          name: Install dependencies
          command: |
            poetry install --no-ansi

      - run:
          name: Install stride
          command: |
            poetry run pip install git+https://github.com/trustimaging/stride

      - restore_cache:
          name: Restore docs cache
          keys:
            - docs-{{ epoch }}
            - docs-

      - run:
          name: Build HTML
          command: |
            OFFLINE=true make docs

      - save_cache:
          key: docs-{{ epoch }}
          paths:
            - docs/generated

      - store_artifacts:
          path: site/
          destination: html


  build_docs_no_cache_and_push:
    docker:
      - image: cimg/python:3.10.10
    resource_class: xlarge
    steps:
      - checkout

      - run:
          name: Install ffmpeg dependency
          command: |
            sudo apt-get update && sudo apt-get install -y ffmpeg

      - run:
          name: Install the latest version of Poetry
          command: |
            curl -sSL https://install.python-poetry.org | python3 -

      - run:
          name: Install dependencies
          command: |
            poetry install --no-ansi

      - run:
          name: Install stride
          command: |
            poetry run pip install git+https://github.com/trustimaging/stride

      - run:
          name: Build docs
          no_output_timeout: 30m
          command: |
            make docs

      - persist_to_workspace:
          root: .
          paths:
            - site


  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "bcibotae@ae.studio"
            git config user.name "bcibotae"
      - add_ssh_keys:
          fingerprints:
            - "fb:b0:89:d9:9a:aa:98:0d:21:2d:a8:f9:9b:98:8d:55"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist site


workflows:
  version: 2

  generate_website_docs:
    when:
      equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - build_docs_no_cache_and_push
      - docs-deploy:
          requires:
            - build_docs_no_cache_and_push

  default:
    when:
      not:
        equal: [ main, << pipeline.git.branch >> ]  # Not building on main branch
    jobs:
      - build_docs:
          name: build_docs_cached
