name: Markdown Link Check

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1