name: Docs artifacts redirector

on: [status]

permissions: read-all
jobs:
  circleci_artifacts_redirector_job:
    if: "${{ startsWith(github.event.context, 'ci/circleci: build_docs') }}"
    permissions:
      statuses: write
    runs-on: ubuntu-20.04
    name: Run CircleCI artifacts redirector
    steps:
      - name: GitHub Action step
        uses: larsoner/circleci-artifacts-redirector-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          api-token: ${{ secrets.CIRCLECI_TOKEN }}
          artifact-path: 0/html/index.html
          circleci-jobs: build_docs
          job-title: Check the rendered docs here!
