name: ci
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.4.0
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Check poetry version
        run: poetry --version

      - name: Install library
        run: poetry install --no-interaction

      - name: Install stride
        run: poetry run pip install git+https://github.com/trustimaging/stride --no-deps

      - run: poetry run mkdocs gh-deploy --force
