name: ci
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3.5.2

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4.6.1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.0
        with:
          version: 1.4.0
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Load cached poetry dependencies
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            venv-${{ runner.os }}

      - name: Install package dependencies
        run: poetry install --no-interaction --no-root

      - name: Install stride
        run: poetry run pip install git+https://github.com/NewtonSander/stride

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install neurotechdevkit
        run: poetry install --only-root

      - name: Checkout gallery
        id: checkout-gallery
        uses: actions/checkout@v3.5.2
        with:
          path: current_pages
          ref: "gh-pages"

      - name: Move generated gallery
        run: |
          mv current_pages/generated /home/runner/work/neurotechdevkit/neurotechdevkit/docs/

      - run: poetry run mkdocs gh-deploy --force
