name: "Pull Request Labeler"

on:
  pull_request:
    branches:
      - "*"

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    if: >
      ${{
        !(
          github.event.label.name == 'release:patch' ||
          github.event.label.name == 'release:minor' ||
          github.event.label.name == 'release:major' ||
          github.event.label.name == 'norelease' ||
          github.event.label.name == 'label_review'
        )
      }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
