name: test

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

defaults:
  run:
    shell: bash

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the neurotechdevkit docker image
        run: |
          docker build . --tag neurotechdevkit

      - name: Test the docker image
        run: |
          docker run neurotechdevkit make test

  test:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.9", "3.10"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3.5.2

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4.6.1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.0
        with:
          version: 1.4.0
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Load cached poetry dependencies
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .cache/pypoetry
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install package dependencies
        run: poetry install --no-interaction --no-root

      - name: Install stride
        run: poetry run pip install git+https://github.com/trustimaging/stride

      - name: Install neurotechdevkit
        run: poetry install --only-root

      - name: Run tests
        run: |
          make test-coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.9'
