name: "Trigger gallery build"
on:
  schedule:
    - cron: '50 14 * * 2' # every Tuesday 2:50pm

jobs:
  trigger-circleci:
    name: "Trigger gallery build on CircleCI"
    runs-on: ubuntu-latest
    steps:
      - name: Trigger circleCI
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.1.0
        env:
          CCI_TOKEN: ${{ secrets.CIRCLECI_TOKEN }}